admins: []
forwards:
- source: -1001128045651
  dest:
  - -1001210537567
  offset: 1061521
  end: null
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  filter:
    text:
      blacklist:
      - badword
    files:
      whitelist:
      - document
      - video
